# Generated by Django 3.1.3 on 2020-12-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filterdesigner', '0003_auto_20201213_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rclowpass',
            old_name='f_Capacitance',
            new_name='s_Capacitance',
        ),
        migrations.RenameField(
            model_name='rclowpass',
            old_name='f_Resistance',
            new_name='s_Resistance',
        ),
    ]
